### ISSUE TITLE
"Blue" icons - for W10 & W11

### ISSUE THREAD

**Issue by TizianoMad** [Mr4Mike4/7-Zip-Filetype-Theme#10]
Hi,
Thank you for providing the new W11 -7zip- icons.
By any chance, could you make this "Blue folders" for this new design ?
Windows 10 Blue 7zip folder:
![Old-7z](https://user-images.githubusercontent.com/90962569/133885676-a2b0c897-bc61-402e-9793-99bfd646de3e.png)
Windows 11 Blue Generic folder :
![Blue](https://user-images.githubusercontent.com/90962569/144341606-eafe94d1-7e75-409c-9c56-85d4bbfce99d.png)
Windows 11 Blue folder with content :
![Blue with content](https://user-images.githubusercontent.com/90962569/144341618-cd7d5d1a-2eea-48ee-8e9a-bc5c5bfbeb9a.png)
Thank you for reading.

**Comment by TizianoMad** [comment]
Thank you so much @Mr4Mike4 !
I guess [this new set](https://www.deviantart.com/th3z/art/Fluent-Blue-7ZIP-Icons-900248101) will soon arrive on the releases page 😃
Finally we have now some decent Zip folders for W11, with a much nicer color than the old yellow we've been having since XP !
Congrats & success 🙌

**Comment by TizianoMad** [comment]
**PS:** I spot just one little mistake with appearing the "**CPIO**" label (x2) instead of "**CAB**" (x0)

**Comment by Mr4Mike4** [comment]
![изображение](https://user-images.githubusercontent.com/6643879/145864112-d54a4a85-4d4f-4b77-98b8-b8ac58e7a3b4.png)
I don't see a mistake. Please take a screenshot

**Comment by TizianoMad** [comment]
Thanx for your fast feed back. 👍

When you sent me the 1st icon files set on DA (see screenshot below), the CAB blue folder was replaced with a duplicate CPIO.

I realized when I reconstructed the DLL file I sent you back, that's why I added it had to be checked.
When I secondly downloaded the DLL file **you** provided here on GitHub, it looked no different.

You can check on ResourceHacker, **# 7 Icon Group** should be "**CAB**" and has the same label as on the proper **# 12 Icon Group "CPIO"**.

(Mega "Fluent Blue" icon files)
![CPIOnoCAB](https://user-images.githubusercontent.com/90962569/145898142-e685ab9b-5476-4d0b-b3c9-54c604a565ab.PNG)

**Comment by Mr4Mike4** [comment]
@TizianoMad 
[7z2106_fluent_blue_ico_fix.7z](https://github.com/Mr4Mike4/7-Zip-Filetype-Theme/releases/tag/21.06)

**Comment by TizianoMad** [comment]
Спасибо тебе за все.
