### ISSUE TITLE
Please add new file type icons against 7-zip-zstd

### ISSUE THREAD

**Issue by FadeMind** [Mr4Mike4/7-Zip-Filetype-Theme#2]
Please add icons for:
FILENAME.DLL (ID ICON)
`ZST`
![20200430-1588250124-001](https://user-images.githubusercontent.com/9846948/80710976-e6aaee00-8aef-11ea-9cb4-8c5f221c1e56.png)
`LZ4`
![20200430-1588250129-001](https://user-images.githubusercontent.com/9846948/80710977-e7438480-8aef-11ea-8d35-db5aa2d6e0f4.png)
 `LZ5`
![20200430-1588250136-001](https://user-images.githubusercontent.com/9846948/80710978-e7438480-8aef-11ea-816d-9b0f380c89ec.png)
 `LIZ`
![20200430-1588250118-001](https://user-images.githubusercontent.com/9846948/80710973-e579c100-8aef-11ea-8105-7cd7ec2b1759.png)

Sources, bins and main project site is here: https://github.com/mcmilk/7-Zip-zstd

See https://github.com/mcmilk/7-Zip-zstd/tree/master/CPP/7zip/Archive/Icons

**Comment by lazerl0rd** [comment]
This would be nice.

**Comment by FadeMind** [comment]
@Mr4Mike4  any progress❓ Regards

**Comment by Mr4Mike4** [comment]
7z21.02-zstd_ico.7z
