### ISSUE TITLE
Need help to install

### ISSUE THREAD

**Issue by 54m4d** [Mr4Mike4/7-Zip-Filetype-Theme#21]
Hi

I have extracted 7z.dll from theme_fluent_blue and replaced it, but my icons did not change on my Win10, is this the correct way?

**Comment by FadeMind** [comment]
Refresh icon cache. Reboot. 
https://www.tenforums.com/tutorials/5645-rebuild-icon-cache-windows-10-a.html

**Comment by 54m4d** [comment]
Yes, now it works.
What about the W11 ribbon? i'm not sure how to install it.

**Comment by 54m4d** [comment]
Yes, now it works.

**Comment by 54m4d** [comment]
@FadeMind Will it also work for 7-Zip-zstd?
