### ISSUE TITLE
Can't disable this in win8.1

### ISSUE THREAD

**Issue by TsXor** [Mr4Mike4/7-Zip-Filetype-Theme#4]
I've reinstalled 7-zip and used 7zTM to change filetype icon, and restarted explorer and system, but I can't disable this theme :(

**Comment by FadeMind** [comment]
Uninstall 7-zip. Reboot. Install 7-zip from original setup file. Reboot.

**Comment by TsXor** [comment]
That worked :) Huge thanks!
