### ISSUE TITLE
Any chance we can get a Win11 theme?

### ISSUE THREAD

**Issue by yurividal** [Mr4Mike4/7-Zip-Filetype-Theme#6]
![image](https://user-images.githubusercontent.com/8555749/124473144-dd25b180-dd96-11eb-8ce4-5d4746c67cb3.png)

**Comment by FadeMind** [comment]
@Mr4Mike4 ping

**Comment by Mr4Mike4** [comment]
Done

**Comment by TizianoMad** [comment]
issue can be closed now ! 😉✌
